export const GET_QUOTE_REQUEST = 'GET_QUOTE_REQUEST';
export const GET_QUOTE_SUCCESS = 'GET_QUOTE_SUCCESS';
export const GET_QUOTE_FAILURE = 'GET_QUOTE_FAILURE';

export const GET_QUOTES_REQUEST = 'GET_QUOTES_REQUEST';
export const GET_QUOTES_SUCCESS = 'GET_QUOTES_SUCCESS';
export const GET_QUOTES_FAILURE = 'GET_QUOTES_FAILURE';

export const RESET_QUOTES = 'RESET_QUOTES';
